export enum OrderStatus {
  PENDING_ACCEPTANCE = "PENDING_ACCEPTANCE",
  ACCEPTED_AWAITING_PAYMENT = "ACCEPTED_AWAITING_PAYMENT",
  PAID_AWAITING_FULFILLMENT = "PAID_AWAITING_FULFILLMENT",
  COMPLETED = "COMPLETED",
  DECLINED = "DECLINED",
}
